caesegatos/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('', include('account.urls', namespace='account')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core import views

app_name='core'

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('anuncios/', views.ver_todos, name='ver_todos'),
    path('anuncios/v/<int:anuncio_id>', views.view_anuncio, name='ver_anuncio'),
    path('add/', views.add_anuncio, name='add_anuncio'),
    path('edit/<int:anuncio_id>', views.update_anuncio, name='edit_anuncio'),
    path('delete/<int:anuncio_id>', views.delete_anuncio, name='delete_anuncio'),
    path('my/', views.user_posts, name='user_posts')
]

templates/anuncio/detalhes.html
{% extends 'base.html' %}

{% block style%}
.img-pet{ height: 500px; }

.container{
    background-color: #fff;
    border-radius: 20px;
    position:relative;
}

.btn-action{
    position: absolute;
    right: 0;
    top: 0;
    margin:15px;
}

{% endblock %}

{% block content %}
<br /><br />
<div class="container p-4 shadow">
    <div class="row px-4">
        <div class="img-pet col-lg-4 p-0 col-12">
            <img src="{{anuncio.image.url}}" width="100%" height="100%" style="object-fit: cover;">
        </div>
        <div class="col-1"></div>
        <div class="col">
            <br/>
            <h2>{{anuncio.titulo}}</h2>
            <p>{{ anuncio.perfil.cidade }}, {{ anuncio.perfil.estado }}<br/><i class="text-muted">{{ anuncio.data_criacao }}</i><br/><br/>Contato: {{ anuncio.perfil.telefone }} | {{anuncio.perfil.user.email }}</p>
            <p>{{ anuncio.descricao }}</p>
        </div>
    </div>
    {% if anuncio.perfil.user == user %}
    <div class="btn-action">
        <a href="{% url 'core:edit_anuncio' anuncio.id %}"><input type="button" class="btn btn-primary shadow-sm" value="Editar"></a>
        <br/><br/>
        <input type="button" class="btn btn-danger shadow-sm" value="Excluir" data-bs-toggle="modal" data-bs-target="#confirmModal">
    </div>
    {% endif %}
    
</div>
<br /><br /><br /><br /><br /><br />


<div class="modal" tabindex="-1" id="confirmModal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Confirmação</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p>Tem certeza que deseja remover o anúncio?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Não, cancelar</button>
          <a href="{% url 'core:delete_anuncio' anuncio.id %}"><button type="button" class="btn btn-primary">Sim, remover</button></a>
        </div>
      </div>
    </div>
  </div>
  
{% endblock %}