caesegatos/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('', include('account.urls', namespace='account')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core import views

app_name='core'

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('anuncios/', views.ver_todos, name='ver_todos'),
    path('anuncios/v/<int:anuncio_id>', views.view_anuncio, name='ver_anuncio'),
    path('add/', views.add_anuncio, name='add_anuncio'),
    path('edit/<int:anuncio_id>', views.update_anuncio, name='edit_anuncio'),
    path('delete/<int:anuncio_id>', views.delete_anuncio, name='delete_anuncio'),
    path('my/', views.user_posts, name='user_posts')
]

core/models.py
from django.db import models
from django.utils import timezone

from account.models import User


class Perfil(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    nome = models.CharField(max_length=50)
    telefone = models.CharField(max_length=15)
    estado = models.CharField(max_length=2)
    cidade = models.CharField(max_length=32)
    bairro = models.CharField(max_length=32)

    def __str__(self):
        return self.nome

class Anuncio(models.Model):
    perfil = models.ForeignKey(Perfil, on_delete=models.CASCADE)
    titulo = models.CharField(max_length=50)
    tipo_animal = models.CharField(max_length=15)
    descricao = models.TextField()
    data_criacao = models.DateTimeField(auto_now_add=True, null=True)
    image = models.ImageField(null=True, blank=True, upload_to='images/')
    def __str__(self):
        return self.titulo

account/forms.py
from django import forms

from account.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(), label='Senha')
    class Meta:
        model = User
        fields = ['first_name', 'last_name','email','password']


class UserLoginForm(forms.ModelForm):
    email = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Email', 'class':'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Senha', 'class':'form-control'}), label='Senha')

    class Meta:
        model = User
        fields = ['email','password']

core/forms.py
from django import forms

from core.models import Anuncio, Perfil

CHOICES = [(None, None), ('Gato', 'Gato'), ('Cachorro', 'Cachorro')]

class PerfilForm(forms.ModelForm):
    estado = forms.CharField(widget=forms.Select)
    cidade = forms.CharField(widget=forms.Select)
    class Meta:
        model = Perfil
        fields = ['telefone','estado','cidade', 'bairro']

class AnuncioForm(forms.ModelForm):
    tipo_animal = forms.ChoiceField(choices=CHOICES, required=True)
    image = forms.FileField(required=True, widget=forms.FileInput(attrs={"accept": "image/png, image/jpeg"}))

    class Meta:
        model = Anuncio
        fields = ['titulo','tipo_animal','descricao', 'image']

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'icons/apple-touch-icon.png'%}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'icons/favicon-32x32.png'%}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'icons/favicon-16x16.png'%}">
    <link rel="manifest" href="icons/site.webmanifest">
    <title>Cães & Gatos | Ínicio</title>
    <link rel="stylesheet" href="{% static 'css/estilo.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <style>
        {% block style %}
        {% endblock %}
    </style>
</head>

<body style="background-color:#ffffff !important">
<!-- Topo -->
<header class="row">
    <a href="{% url 'core:inicio' %}" class="col">
        <div class="logo">
            <img src="{% static 'img/bg_logo.png' %}" class="bg_logo">
            <img src="{% static 'img/logo.png' %}" class="logo_img">
        </div>
    </a>
    <nav class="navbar navbar-expand menu-light col">
        <div class="container-fluid justify-content-end me-2">
            <ul class="navbar-nav mb-2 navbar-text">
                <li class="nav-item"><a class="nav-link" href="{% url 'core:ver_todos' %}" >Quero Adotar</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'core:add_anuncio' %}">Quero Anunciar</a></li>
                {% if request.user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="/logout/"><strong>Encerrar sessão</strong></a>
                {% else %}
                    <li class="nav-item"><a class="nav-link" data-bs-toggle="offcanvas" href="#offcanvas-signup">Cadastre-se</a></li>
                    <li class="nav-item"><a class="nav-link" data-bs-toggle="offcanvas" href="#offcanvas-login"><strong>Entrar</strong></a>
                {% endif %}
                </li>
            </ul>
        </div>
    </nav>
</header>

<!-- Offcanvas Login -->

<div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvas-login" aria-labelledby="offcanvasExampleLabel">
    <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasExampleLabel"></h5>
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
        <h5 style="text-align: center;">Faça login</h5>
        <br/>
        <form action="/login/" method="post">
            {% csrf_token %}
            {{ form.email }}
            <br/>
            {{ form.password }}
            <br/>
            <button class="btn light btn-lg text-light" type="submit" style="width: 100%;">Entrar</button>
            <br/>
            <br/>
            Não tem uma conta? <a href="#offcanvas-signup" data-bs-toggle="offcanvas"><strong>Clique aqui e cadastre-se</strong></a>
        </form>
    </div>
</div>

<!--OffCanvas Signup-->

<div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvas-signup" aria-labelledby="offcanvasExampleLabel">
    <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasSignupLabel"></h5>
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
        <h5 style="text-align: center;">Cadastre-se</h5>
        <br/>
        <form action="/signup/" method="post">
            {% csrf_token %}
            <div class="row g-3 mb-3">
                <input class="form-control" type="text" name="first_name" id="id_first_name" placeholder="Nome" maxlength="50">
            </div>
            <div class="row g-3 mb-3">
                <input class="form-control" type="text" name="last_name" id="id_last_name" placeholder="Sobrenome" maxlength="50">
            </div>
            
            <div class="row g-3 mb-3">
            
                <input class="form-control" type="text" name="telefone" id="id_telefone" placeholder="Telefone" maxlength="15">
            
            </div>
            <div class="row g-3 mb-3">
                <div class="col-6 p-0">
                    <select class="form-select select-estado" name="estado" id="id_estado">
                        <option value="">Estado</option>
                    </select>
                </div>
                <div class="col-6 p-0">
                    <select class="form-select select-cidade" name="cidade" id="id_cidade">
                        <option value="">Cidade</option>
                    </select>
                </div>
            </div>
            <div class="row g-3 mb-3">
                <input class="form-control" type="text" name="bairro" id="id_bairro" placeholder="Bairro" maxlength="32">
            </div>
            <div class=" row g-3 mb-3">
                <input class="form-control" type="email" name="email" id="id_email" placeholder="Email" maxlength="64">
            </div>
            <div class="row g-3 mb-3">
                <input class="form-control" type="password" name="password" id="id_password" placeholder="Senha">
            </div>
            <button class="btn light btn-lg text-light" type="submit" style="width: 100%;">Salvar</button>
            <br/>
            <br/>
            <a href="#offcanvas-login" data-bs-toggle="offcanvas">Voltar à tela de login</a>
        </form>
    </div>
</div>

<div class="container-fluid" style="background-color: var(--blue);">
    {% block content %}
    {% endblock %}
</div>

<!-- Footer -->

<footer class="row" style="background-color: var(--blue);">
    <div class="col d-flex justify-content-center">
        <img src="{% static 'img/logo_branca.png' %}">
    </div>
</footer>
</body>
<script src="{% static 'js/api.js' %}"></script>
{% block scripts %}
{% endblock %}

</html>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'icons/apple-touch-icon.png'%}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'icons/favicon-32x32.png'%}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'icons/favicon-16x16.png'%}">
    <link rel="manifest" href="icons/site.webmanifest">
    <title>Cães & Gatos | Ínicio</title>
    <link rel="stylesheet" href="{% static 'css/estilo.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</head>

<body>
<!-- Topo -->
<header class="row">
    <a href="{% url 'core:inicio' %}" class="col">
        <div class="logo">
            <img src="{% static 'img/bg_logo.png' %}" class="bg_logo">
            <img src="{% static 'img/logo.png' %}" class="logo_img">
        </div>
    </a>
    <nav class="navbar navbar-expand menu col">
        <div class="container-fluid justify-content-end me-2">
            <ul class="navbar-nav mb-2 navbar-text">
                <li class="nav-item"><a class="nav-link" href="#recem-chegados" >Quero Adotar</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'core:add_anuncio' %}">Quero Anunciar</a></li>
                {% if request.user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'core:user_posts' %}">Meus anúncios</a>
                    <li class="nav-item"><a class="nav-link" href="/logout/"><strong>Encerrar sessão</strong></a>
                {% else %}
                    <li class="nav-item"><a class="nav-link" data-bs-toggle="offcanvas" href="#offcanvas-signup">Cadastre-se</a></li>
                    <li class="nav-item"><a class="nav-link" data-bs-toggle="offcanvas" href="#offcanvas-login"><strong>Entrar</strong></a>
                {% endif %}
                </li>
            </ul>
        </div>
    </nav>
</header>

<!-- Offcanvas Login -->

<div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvas-login" aria-labelledby="offcanvasExampleLabel">
    <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasExampleLabel"></h5>
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
        <h5 style="text-align: center;">Faça login</h5>
        <br/>
        <form action="/login/" method="post">
            {% csrf_token %}
            {{ form.email }}
            <br/>
            {{ form.password }}
            <br/>
            <button class="btn light btn-lg text-light" type="submit" style="width: 100%;">Entrar</button>
            <br/>
            <br/>
            Não tem uma conta? <a href="#offcanvas-signup" data-bs-toggle="offcanvas"><strong>Clique aqui e cadastre-se</strong></a>
        </form>
    </div>
</div>

<!--OffCanvas Signup-->

<div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvas-signup" aria-labelledby="offcanvasExampleLabel">
    <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasSignupLabel"></h5>
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
        <h5 style="text-align: center;">Cadastre-se</h5>
        <br/>
        <form action="/signup/" method="post">
            {% csrf_token %}
            <div class="row g-3 mb-3">
                <input class="form-control" type="text" name="first_name" id="id_first_name" placeholder="Nome" maxlength="50">
            </div>
            <div class="row g-3 mb-3">
                <input class="form-control" type="text" name="last_name" id="id_last_name" placeholder="Sobrenome" maxlength="50">
            </div>
            
            <div class="row g-3 mb-3">
            
                <input class="form-control" type="text" name="telefone" id="id_telefone" placeholder="Telefone" maxlength="15">
            
            </div>
            <div class="row g-3 mb-3">
                <div class="col-6 p-0">
                    <select class="form-select" name="estado" id="id_estado_form">
                        <option value="">Estado</option>
                    </select>
                </div>
                <div class="col-6 p-0">
                    <select class="form-select" name="cidade" id="id_cidade">
                        <option value="">Cidade</option>
                    </select>
                </div>
            </div>
            <div class="row g-3 mb-3">
                <input class="form-control" type="text" name="bairro" id="id_bairro" placeholder="Bairro" maxlength="32">
            </div>
            <div class=" row g-3 mb-3">
                <input class="form-control" type="email" name="email" id="id_email" placeholder="Email" maxlength="64">
            </div>
            <div class="row g-3 mb-3">
                <input class="form-control" type="password" name="password" id="id_password" placeholder="Senha">
            </div>
            <button class="btn light btn-lg text-light" type="submit" style="width: 100%;">Salvar</button>
            <br/>
            <br/>
            <a href="#offcanvas-login" data-bs-toggle="offcanvas">Voltar à tela de login</a>
        </form>
    </div>
</div>

<!-- Banner -->
<section>
    <div class="container my-4 pt-4">
        <div class="row align-items-center text-light pb-4">
            <div class="col">
                <h1 class="display-5 fw-bold">Seu novo amigo pode estar mais perto do que você imagina!</h1>
                <br/>
                <p class="fs-5">Encontre vários anjinhos à espera de um lar, na sua região. </p>
                <br/>
                <a href="{% url 'core:ver_todos' %}">
                    <button class="btn btn-lg btn-light w-50" type="button">Buscar agora</button>
                </a>
            </div>
            <div class="col d-flex justify-content-end">
                <img src="{% static 'img/pet.png' %}" width="90%">
            </div>
        </div>
    </div>
</section>

<!-- Recem chegados -->

<section id="recem-chegados" class="recem-chegados mb-4">
    <img src="{% static 'img/pegadas.png' %}" style="position: absolute; right: 0;">

    <div class="container pt-4">
        <h4>Recém chegados</h4>
        <br/>
        <div class="row">
            {% for anuncio in recentes %}
                <div class="col-12 col-sm-12 col-md-4 col-lg-3 p-2" style="height: 300px;">
                    <div style="height: 100%;">
                        <a href="{% url 'core:ver_anuncio' anuncio.id %}" class="link">
                            <div class="pet-card" width="100%" height="100%">
                                <img src="{{ anuncio.image.url }}" class="card-img-top" width="100%" height="200px">
                                <div class="card-body" style="text-align: center;">
                                    <h5 class="card-title"><strong>{{ anuncio.titulo }}</strong></h5>
                                    <p class="card-text">{{ anuncio.perfil.cidade }}, {{ anuncio.perfil.estado }}</p>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="py-4" style="text-align: center;">
            <a href="{% url 'core:ver_todos' %}">
                <button class="btn btn-lg text-light" type="button" style="background-color: var(--blue);">
                    Ver mais
                </button>
            </a>
        </div>
    </div>
    <br/>
    <br/>
    <br/>
</section>

<!-- Footer -->

<footer class="row">
    <div class="col d-flex justify-content-center">
        <img src="{% static 'img/logo_branca.png' %}">
    </div>
</footer>
</body>
<script src="{% static 'js/api.js' %}"></script>
</html>

templates/result.html
{% extends 'base.html' %}


{% block style %}
  .container{
    min-height: 700px;
  }
{% endblock %}

{% block content %}
<div class="container pt-4">
  <form method="get">
    <div class="row align-items-end">
      <div class="col text-light">
        <label for="id_tipo_animal">Tipo de animal:</label>
        <select name="tipo_animal" class="form-select" id="id_tipo_animal">
          <option value="" selected>---------</option>
          <option value="Cachorro">Cachorro</option>
          <option value="Gato">Gato</option>
        </select>
      </div>
      <div class="col text-light">
        <label for="id_estado">Estado:</label>
        <select name="estado" class="form-select select-estado" id="id_estado">
          <option value="" selected>---------</option>
        </select>
      </div>
      <div class="col text-light">
        <label for="id_cidade">Cidade:</label>
        <select name="cidade" class="form-select select-cidade" id="id_cidade">
          <option value="" selected>---------</option>
        </select>
      </div>
      <div class="col d-flex align-items-end">
        <input type="submit" value="Buscar" onclick="saveKeywords()" class="btn btn-light">
      </div>
    </div>
  </form>
  <br />
  <br />
  <div class="row">
    {% for anuncio in anuncios %}
    <div class="col-12 col-sm-12 col-md-4 col-lg-3 p-2" style="height: 300px;">
      <div style="height: 100%;">
        <a href="{% url 'core:ver_anuncio' anuncio.id %}" class="link">
          <div class="pet-card" width="100%" height="100%" style=" background-color: var(--orange);">
            <img src="{{ anuncio.image.url }}" class="card-img-top" width="100%" height="200px">
            <div class="card-body" style="text-align: center;">
              <h5 class="card-title"><strong>{{ anuncio.titulo }}</strong></h5>
              <p class="card-text">{{ anuncio.perfil.cidade }}, {{ anuncio.perfil.estado }}</p>
            </div>
          </div>
        </a>
      </div>
    </div>
    {% endfor %}
  </div>
  <div class="py-4 w-100" style="text-align: center;">
    <span class="step-links text-light">
      {% if anuncios.has_previous %}
      <a href="?page={{ anuncios.previous_page_number }}&tipo_animal={{tipo_animal}}&estado={{estado}}&cidade={{cidade}}"
        class="text-light"><strong>
          < Anterior</strong></a>
      {% endif %}

      <span class="current">
        &nbsp Página {{ anuncios.number }} de {{ anuncios.paginator.num_pages }}. &nbsp
      </span>

      {% if anuncios.has_next %}
      <a href="?page={{ anuncios.next_page_number }}&tipo_animal={{tipo_animal}}&estado={{estado}}&cidade={{cidade}}"
        class="text-light"><strong>Próxima
          ></strong></a>
      {% endif %}
    </span>
  </div>
</div>
{% endblock %}

{% block scripts %}
<script>
  const tipoField = document.getElementById('id_tipo_animal')
  const estadoField = document.getElementById('id_estado')
  const cidadeField = document.getElementById('id_cidade')

  {% if tipo_animal == '' and estado == '' and cidade == '' %}
    window.localStorage.clear()
  {% else %}
    loadKey(tipoField,'tipo_animal')
    loadKey(estadoField,'uf_nome')
    loadKey(cidadeField,'cidade')
  {% endif %}

  function loadKey(field, itemName) {
    var data = window.localStorage.getItem(itemName)
    if(data != null)
      field.value = data
    console.log(itemName+': '+data)
  }

  console.log(window.localStorage.getItem('uf_nome'))

  function saveKeywords() {
    window.localStorage.setItem('tipo_animal', tipoField.value)
    window.localStorage.setItem('uf_sigla', estadoField.options[estadoField.selectedIndex].value)
    window.localStorage.setItem('uf_nome', estadoField.options[estadoField.selectedIndex].text)
    window.localStorage.setItem('cidade', cidadeField.value)
  }
</script>
{% endblock %}

templates/user_posts.html
{% extends 'base.html' %}


{% block style %}
  .container{
    min-height: 700px;
    
  }
  .post{
    background-color: #fff;
    border-radius: 20px;
    position:relative;
}

a{
    text-decoration: none;
}

{% endblock %}

{% block content %}
<div class="container pt-4 text-light">
    <h3>Meus anúncios</h3>
  <div class="row">
    {% for anuncio in anuncios %}
    <div class="col-12 post p-4 mb-2">
        <a href="{% url 'core:ver_anuncio' anuncio.id %}" class="text-dark">
            <div class="row">
                <div class="col col-md-4 col-lg-3 col-xl-2">
                    <img src="{{ anuncio.image.url }}" width="200px" height="200px">        
                </div>
                <div class="col">
                    <br/>
                    <h2>{{anuncio.titulo}}</h2>
                    <p>{{ anuncio.perfil.cidade }}, {{ anuncio.perfil.estado }}<br/><i class="text-muted">{{ anuncio.data_criacao }}</i></p>
                </div>
            </div>
        </a>
    </div>
    {% endfor %}
  </div>
{% endblock %}